# Generated by Django 4.0.2 on 2022-02-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='urlToImage',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
